name: Simple Test Run

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

permissions:
  contents: read
  actions: read

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          tesseract-ocr \
          tesseract-ocr-eng \
          poppler-utils \
          libgl1-mesa-dri \
          libglib2.0-0
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov reportlab pillow
    
    - name: Download spaCy model
      run: |
        python -m spacy download en_core_web_lg
    
    - name: Setup test data
      run: |
        python .github/scripts/setup_test_data.py
        echo "Setup script completed. Checking results:"
        ls -la example_data/ || echo "example_data directory not found"
    
    - name: Verify test data files
      run: |
        echo "Checking if critical test files exist:"
        ls -la example_data/
        echo "Checking for specific PDF files:"
        ls -la example_data/*.pdf || echo "No PDF files found"
        echo "Checking file sizes:"
        find example_data -name "*.pdf" -exec ls -lh {} \;
    
    - name: Run CLI tests
      run: |
        cd test
        python test.py
    
    - name: Run tests with pytest
      run: |
        pytest test/test.py -v --tb=short
